//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public int Id { get; set; }
        public string P_Category { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public string Volume_Number { get; set; }
        public string Year { get; set; }
        public string Page_Number { get; set; }
        public string Shelf_Num { get; set; }
    }
}
