//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_by { get; set; }
    }
}
